version: '3'
services:

  lb-api:
    image: dev-swagger-hapi-api
    #image: wilfongjt/lb-api
    build:
      context: .
    command: >
      sh -c "npm install && npm install nodemon && npm run dev"
    volumes:
      - .:/usr/src/api
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=0.0.0.0
      - PORT=5555
      #- APP_ API=${HAPI_PORT}
      #- APP_ API_PORT=${HAPI_ PORT}
      #- APP_ API_HOST=${HAPI_ HOST}
      #- HAPI_ PORT=${HAPI_ PORT}
      #- HAPI_ HOST=${HAPI_ HOST}
