# This is a basic workflow to help you get started with Actions
# remove and leave space
name: CI_Api_Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install testing, @hapi/lab and @hapi/code
      - name: Install Lab and Code
        run: npm install --save-dev @hapi/lab @hapi/code
        #working-directory: lyb-api
      
      # Runs a set of commands using the runners shell
      - name: Run Tests
        run: npm run test
        #working-directory: lyb-api
      
      # This is the heroku deploy action
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lyb-api" #Must be unique in Heroku
          heroku_email: "wilfongjt@gmail.com"
          
